### ISSUE TITLE
event info section

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#25]
<img width="450" alt="screen shot 2015-08-02 at 2 48 11 pm" src="https://cloud.githubusercontent.com/assets/1305229/9028217/8861f1f2-3925-11e5-8be3-b72f2dce377a.png">

**Comment by kprakobkit** [comment]
Just find images on google for now

**Comment by ingachen** [comment]
@kprakobkit thinking about redesigning these to make it more rustic - don't think the image as a bg fits the current style, unless you disagree? 

also, do you have details of the thailand venue / schedule / image? otherwise can leave placeholders

**Comment by kprakobkit** [comment]
@ingachen -  I kind of like the big image but agree that it doesn't fit with the current style. let's try the redesign. placeholders for now for the the thailand venue. Thanks!

**Comment by ingachen** [comment]
@kprakobkit What do you think about either of these?

This one has the white border around the venue image so it matches your photo gallery aesthetic
 ![image](https://cloud.githubusercontent.com/assets/8811461/9030600/b3000adc-3959-11e5-9c68-34641ad46706.png)

This one still gives you the big image but it's muted so you can overlay text and doesn't seem too strong. The pinkish hue can be changed to any color also - blue, gray, etc. 
![image](https://cloud.githubusercontent.com/assets/8811461/9030605/c3ad628a-3959-11e5-992c-8d42e89f27cd.png)

Also - do you know what font Seline used? I think it matches the rustic theme best but don't know what it's called - I'll need to download it.

**Comment by kprakobkit** [comment]
Let's go with the second option. Also am following up with Seline on the font - will let you know ASAP.

**Comment by kprakobkit** [comment]
@achiu8 
The content runs off the section on mobile:

<img width="344" alt="screen shot 2015-08-03 at 1 01 18 am" src="https://cloud.githubusercontent.com/assets/1305229/9033364/3005e85a-397b-11e5-8046-80b740f3180b.png">

**Comment by kprakobkit** [comment]
@ingachen font information is in the wiki page.

**Comment by achiu8** [comment]
Thoughts on making this section tinted with a color? Or do you want to rethink the design? Very hard to read as is.

@ingachen

**Comment by kprakobkit** [comment]
agree - also what about have the left part be saratoga wedding and the right party be thailand wedding?

**Comment by achiu8** [comment]
Yeah, was thinking that as well. I'll tweak.
