### ISSUE TITLE
nav bar styling

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#26]

**Comment by kprakobkit** [comment]
thoughts on not making it transparent?
Transparent:
<img width="1374" alt="screen shot 2015-08-04 at 11 33 33 pm" src="https://cloud.githubusercontent.com/assets/1305229/9079643/48d9a79a-3b01-11e5-828d-891fb55c1b45.png">

Not transparent:
<img width="1062" alt="screen shot 2015-08-04 at 11 33 45 pm" src="https://cloud.githubusercontent.com/assets/1305229/9079642/48d969f6-3b01-11e5-9093-b855ed4f2d35.png">

**Comment by achiu8** [comment]
Not transparent looks good to me.
