### ISSUE TITLE
wedding party section

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#27]
<img width="454" alt="screen shot 2015-08-02 at 2 53 33 pm" src="https://cloud.githubusercontent.com/assets/1305229/9028232/4e55221c-3926-11e5-9cba-b4f19804052a.png">

**Comment by kprakobkit** [comment]
Colors can change - play around to see what works.

Interaction wise - something like the one on this site - http://www.katieplusluke.com/
Where clicking/hovering over the squares reveal their face, and clicking on it shows a modal of the image. Use placeholder images for now, so it can be easily replaced with a real image.

**Comment by ingachen** [comment]
![image](https://cloud.githubusercontent.com/assets/8811461/9054876/76ff13c0-3a3a-11e5-9437-d16bc91464fc.png)

When you hover over the box, it will change to the picture of the bridesmaid/groomsmen.

**Comment by kprakobkit** [comment]
I like it - I'll take a stab at the second design today.

**Comment by kprakobkit** [comment]
I'm thinking of adding a modal to display a bigger picture when the user clicks on the picture of the bridesmaid/groomsmen. Thoughts?

**Comment by achiu8** [comment]
Sounds good to me.
