### ISSUE TITLE
image carousel - image preview looks ugly on mobile

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#28]
<img width="332" alt="screen shot 2015-08-02 at 3 00 37 pm" src="https://cloud.githubusercontent.com/assets/1305229/9028245/409ef548-3927-11e5-9b91-1b27a06217a2.png">

**Comment by kprakobkit** [comment]
I was thinking we can hide it on mobile view.

**Comment by achiu8** [comment]
Agree.
