### ISSUE TITLE
style thankyou/confirmation message after submitting rsvp form

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#30]
Right now it looks like this:
<img width="1038" alt="screen shot 2015-08-02 at 3 04 00 pm" src="https://cloud.githubusercontent.com/assets/1305229/9028263/f5c7cb84-3927-11e5-87b1-04644dfceea4.png">

Just use your imagination on how to make it look better.

**Comment by ingachen** [comment]
@kprakobkit Any thoughts on these? If either of you were really ambitious, you could have the envelope fold up into the paper airplane and animate. Less involved would be to close the envelope and have it fade away then show this screen. No animation would be just "submit"-> this screen. 

The text would be in the site-wide font of course, I just don't have it on my comp.

![image](https://cloud.githubusercontent.com/assets/8811461/9294949/2f972f90-4412-11e5-9567-06a4d036d660.png)

![image](https://cloud.githubusercontent.com/assets/8811461/9294951/3be31020-4412-11e5-948c-4386aa5a01e1.png)

**Comment by kprakobkit** [comment]
Ooo yeah! Where should it be displayed?

**Comment by achiu8** [comment]
Thinking the envelope / form would disappear and show this.

**Comment by achiu8** [comment]
After submit

**Comment by kprakobkit** [comment]
okay yeah i like it

**Comment by kprakobkit** [comment]
@achiu8 you wanna take a stab at it while i work on the other issues?

**Comment by achiu8** [comment]
Yeah, will work on that and the overflow issue.

**Comment by kprakobkit** [comment]
I also think we should show a loading spinner, instead of the message that shows at the bottom of the envelope. what do you think?

**Comment by kprakobkit** [comment]
And adding like an instruction to improve usability. got some feedback that users might not know to enter their first and last name to see the rest of the form.

EDIT: what about showing the attending-options dropdown?

**Comment by achiu8** [comment]
Still need submit spinner right?
