### ISSUE TITLE
story section

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#31]
![07302015_00-home_01 hi](https://cloud.githubusercontent.com/assets/1305229/9029080/99eb2e54-3941-11e5-9c6a-9b9ed6ca406f.jpg)
![07302015_00 5-home-to-story_01](https://cloud.githubusercontent.com/assets/1305229/9029081/99edbe76-3941-11e5-8408-0b167b911aeb.jpg)
![07302015_00 5-home-to-story_02](https://cloud.githubusercontent.com/assets/1305229/9029083/99efe3ea-3941-11e5-89a1-d574af53b106.jpg)
![07302015_00 5-home-to-story_03](https://cloud.githubusercontent.com/assets/1305229/9029082/99efb618-3941-11e5-9377-1455b2f9e901.jpg)
![07302015_01_story_00](https://cloud.githubusercontent.com/assets/1305229/9029084/99f0409c-3941-11e5-9a3f-8e606a5f6584.jpg)
![07302015_01_story_01](https://cloud.githubusercontent.com/assets/1305229/9029085/99f11f30-3941-11e5-8e0d-1a74a0603d6b.jpg)
![07302015_01_story_02](https://cloud.githubusercontent.com/assets/1305229/9029086/99fe6c6c-3941-11e5-870e-eb4f1fc1099b.jpg)
![07302015_01_story_03](https://cloud.githubusercontent.com/assets/1305229/9029088/9a01329e-3941-11e5-9207-c555fca9174d.jpg)
![07302015_01_story_04](https://cloud.githubusercontent.com/assets/1305229/9029087/9a000bf8-3941-11e5-844a-d97528530f67.jpg)
![07302015_01_story_05](https://cloud.githubusercontent.com/assets/1305229/9029090/9a02b7d6-3941-11e5-8b57-b824d0f0e167.jpg)
![07302015_01_story_06](https://cloud.githubusercontent.com/assets/1305229/9029089/9a02cbd6-3941-11e5-961a-c69d63d22d44.jpg)

**Comment by kprakobkit** [comment]
But without fixed background because mobile does not support fixed background.

**Comment by kprakobkit** [comment]
Waiting on artwork from Seline.

**Comment by kprakobkit** [comment]
what do you think about doing something like this with the logo?

<img width="1078" alt="screen shot 2015-08-14 at 9 54 25 pm" src="https://cloud.githubusercontent.com/assets/1305229/9287546/1dd59056-42cf-11e5-8f14-5ff88d6b803e.png">

**Comment by achiu8** [comment]
I like it
