### ISSUE TITLE
RSVP form design

### ISSUE THREAD

**Issue by achiu8** [achiu8/natandp#34]

**Comment by ingachen** [comment]
@kprakobkit any thoughts on an envelope style for the rsvp section? there can be an animation of the paper coming out the envelope when you scroll to this section. text can appear as you fill in each blank (e.g. at first it will show (your name only...) then when you type your name, it will show you the next dropdown) 
![image](https://cloud.githubusercontent.com/assets/8811461/9032206/038521ec-3971-11e5-8cd8-b0b81d3a398b.png)

![image](https://cloud.githubusercontent.com/assets/8811461/9032222/3e51219a-3971-11e5-8830-76826e156c9f.png)

![image](https://cloud.githubusercontent.com/assets/8811461/9032227/46c1575a-3971-11e5-96c3-32e9d4651c82.png)

**Comment by kprakobkit** [comment]
@inga Nat and I like the envelop idea - can we try it in black lettering on a grayscale?

**Comment by ingachen** [comment]
@kprakobkit 
completely gray scale ![image](https://cloud.githubusercontent.com/assets/8811461/9054128/9f2df09e-3a32-11e5-9aa4-309914e399f6.png)

grayscale with the pink accent. this accent color can be another color too, e.g. light blue, etc. whatever accent color we decide for the site. also, if we're going to have the whole site as a gray bg, this envelope will be likely be too gray if overlayed on a gray bg. ![image](https://cloud.githubusercontent.com/assets/8811461/9054132/aae185a4-3a32-11e5-9e31-74a72b82612a.png)

**Comment by ingachen** [comment]
@kprakobkit on the gray bg 
![image](https://cloud.githubusercontent.com/assets/8811461/9054308/8dbba1f6-3a34-11e5-9d79-d009332b0af4.png)
need to play with _something_ to make this not like we're watching black and white tv

**Comment by ingachen** [comment]
are there any accent colors you would want to add to the website? or you want all gray?

**Comment by kprakobkit** [comment]
lol...agree with the black and white tv

Can we try - gold accents? like inner lining of card to be gold - lettering can have accents of navy blue, like the input fields. thoughts?

**Comment by ingachen** [comment]
![image](https://cloud.githubusercontent.com/assets/8811461/9054396/a76a1da2-3a35-11e5-8066-a9c36f12d00b.png)
hmm.. don't like it as much. because it's fighting soft (gray) with hard (navy / gold) 

![image](https://cloud.githubusercontent.com/assets/8811461/9054475/aaa44122-3a36-11e5-92bb-4b7a7fe2368c.png)

![image](https://cloud.githubusercontent.com/assets/8811461/9054509/25d5cadc-3a37-11e5-896d-2ff937d62561.png)

![image](https://cloud.githubusercontent.com/assets/8811461/9054523/3e654ce4-3a37-11e5-9ec1-0635957f6ce2.png)

**Comment by kprakobkit** [comment]
What about we park designing the envelope for now, and play around with giving some accent to the current rsvp form design. I don't want us to spend too much time on the rsvp form.

**Comment by kprakobkit** [comment]
yo how's this going?

**Comment by achiu8** [comment]
Been kinda busy with work.. will try to get to it tonight.

**Comment by kprakobkit** [comment]
yo no worries
