### ISSUE TITLE
colors.........

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#37]
@ingachen @johnlin1214 @achiu8 - 
nat said she wanted less colors and have it be mostly grey so i played around and came up with something like this, which she likes better:
<img width="1423" alt="screen shot 2015-08-03 at 12 49 28 am" src="https://cloud.githubusercontent.com/assets/1305229/9033140/935c99b4-3979-11e5-93ce-a2dd14811834.png">
<img width="1388" alt="screen shot 2015-08-03 at 12 49 36 am" src="https://cloud.githubusercontent.com/assets/1305229/9033139/935af686-3979-11e5-8286-e944a362b755.png">
<img width="1348" alt="screen shot 2015-08-03 at 12 49 42 am" src="https://cloud.githubusercontent.com/assets/1305229/9033138/935ad7d2-3979-11e5-98ef-34962db35ff0.png">

I'll track these changes locally on a branch for now.

Now there is not visual divide between each section, any thoughts on how to accomplish this?

**Comment by achiu8** [comment]
Was going to suggest the single color background as well. I can mess with the section divides--thinking maybe a line segment (centered, that's only a fraction of the the width of the page) and a symbol of some kind.

**Comment by kprakobkit** [comment]
sounds good.

**Comment by kprakobkit** [comment]
closing this since it's been implemented.
