### ISSUE TITLE
Styling picture section

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#38]
@ingachen @achiu8 @johnlin1214
Any thoughts on how to style the pictures section...whatever i try it just looks off.

<img width="889" alt="screen shot 2015-08-03 at 1 05 03 am" src="https://cloud.githubusercontent.com/assets/1305229/9033433/b6aae7d4-397b-11e5-8ef0-92a18f233b09.png">

My thoughts:
- get rid of thumbs
- have a wooden frame; ignore the background color since it will likely change to light grey.
- have left and right chevrons
- image automatically changes every x seconds.

**Comment by achiu8** [comment]
Agree with all your suggestions, except maybe the wooden frame. How do you feel about polaroid-like frames, like the elastic stack library?

**Comment by kprakobkit** [comment]
okay - i do like the polaroid. i'll play around with it.

**Comment by achiu8** [comment]
@kprakobkit Are you going to just let it be automatic? No chevrons?

**Comment by kprakobkit** [comment]
Chevrons are still there - they might not be as visible. Also chevrons aren't displaying on production - see below - because assets are not properly loaded. I'll add the issue to #45 since they are related.

<img width="154" alt="screen shot 2015-08-03 at 10 31 06 pm" src="https://cloud.githubusercontent.com/assets/1305229/9053849/8299895a-3a2f-11e5-90a8-c6448b5aca5d.png">
<img width="710" alt="screen shot 2015-08-03 at 10 31 27 pm" src="https://cloud.githubusercontent.com/assets/1305229/9053850/829a0150-3a2f-11e5-85a7-15fffc39faef.png">
