### ISSUE TITLE
install fonts

### ISSUE THREAD

**Issue by achiu8** [achiu8/natandp#45]

**Comment by kprakobkit** [comment]
Assets for slick.ttf, slick.woff are not properly loaded on production - see image below.
<img width="710" alt="screen shot 2015-08-03 at 10 31 27 pm" src="https://cloud.githubusercontent.com/assets/1305229/9053864/b72830ea-3a2f-11e5-9498-228000759103.png">

**Comment by achiu8** [comment]
Think you might have to do what I did? Explicitly have them precompile.

**Comment by achiu8** [comment]
I'll try to fix it.

**Comment by kprakobkit** [comment]
fonts not showing on production:
<img width="1331" alt="screen shot 2015-08-03 at 11 41 18 pm" src="https://cloud.githubusercontent.com/assets/1305229/9054726/3428e752-3a39-11e5-9933-49595950f057.png">

**Comment by kprakobkit** [comment]
@achiu8 @johnlin1214 
can you push directly to heroku to test?

remote for fetch and push is https://git.heroku.com/boiling-crag-6002.git
