### ISSUE TITLE
lol...something broke the navbar on mobile...again

### ISSUE THREAD

**Issue by kprakobkit** [achiu8/natandp#65]
should we consider an alternative to the current navbar on mobile?

**Comment by kprakobkit** [comment]
it broke going from commit 098c600 to 0f69412...which makes no sense because the changes are extracting variables in the wedding_party.scss

You guys have any idea?

<img width="1351" alt="screen shot 2015-08-06 at 5 23 50 pm" src="https://cloud.githubusercontent.com/assets/1305229/9126252/0abdfc6c-3c60-11e5-94aa-e842724af52c.png">

**Comment by achiu8** [comment]
What broke?

**Comment by kprakobkit** [comment]
<img width="329" alt="screen shot 2015-08-06 at 8 42 03 pm" src="https://cloud.githubusercontent.com/assets/1305229/9128351/a3109964-3c7b-11e5-9494-03c7def4cc08.png">

**Comment by achiu8** [comment]
Goddamnit.. how do you know it broke on that commit?

**Comment by kprakobkit** [comment]
did a git checkout until i found when it worked

**Comment by achiu8** [comment]
Oh man.. haha I can look into if you want. Or we can just get rid of it...

**Comment by kprakobkit** [comment]
i'll take a stab at it.
