### ISSUE TITLE
event info additional comments?

### ISSUE THREAD

**Issue by achiu8** [achiu8/natandp#74]
@kprakobkit 

Let me know.

**Comment by kprakobkit** [comment]
wasn't the background grey before? that made the pictures more visible. 

Did you remove the icons on purpose?

also can you add the time, 11am to the saratoga wedding? and say TBD for thailand.

**Comment by achiu8** [comment]
Changed it because text wasn't visible. But can change back if you think it was better that way.

Icons kinda made sense for each event, but not sure if they do for the weddings.. we can look for other ones to use if you have any ideas.

Will add the times.

**Comment by kprakobkit** [comment]
I really want the picture to be more visible. Any thoughts on how to do that? 

Also, would it be much to do:
- As is on desktop with a ring in between the two pictures, and a header that says 'Event Information',
  - additional content to add:
  - Ceremony at 11 (with cake icon)
  - Brunch with Sangria and Mimosa to follow (with a champagne icon)
- On mobile
  - each event is it's own row, and the header and content stays the same

**Comment by achiu8** [comment]
So seems like the more visible the pictures, the less visible the text is, especially without a tint. Other options would be to make the text more bold, blur the image, or add the container for the text (and just have the image clear around it.

**Comment by achiu8** [comment]
Should find better images (at least for the Thailand side) that isn't of someone else's wedding haha.. Would be awesome if it is actually of the Thailand venue, or at least in the country..

**Comment by kprakobkit** [comment]
Ceremony at Holy Redeemer Church at14:00pm
Reception at Bankampoo at 6:00pm
https://www.facebook.com/BankampuWeddings
http://www.bankampu.com/

**Comment by achiu8** [comment]
Ceremony is 14:00 or 4:00pm?

**Comment by kprakobkit** [comment]
2pm/14pm

**Comment by kprakobkit** [comment]
The events info section looks weird on mobile. Can we try having each event be in it's own row on mobile?

<img width="328" alt="screen shot 2015-08-14 at 9 18 09 am" src="https://cloud.githubusercontent.com/assets/1305229/9278414/7b86a0b0-4265-11e5-9a69-3299059a2302.png">

**Comment by achiu8** [comment]
Yeah, will fix.
